#!/bin/bash

filename="$HOME/goals.txt"

function add_goal() {
  DATE=$(date +%s)

  (
  echo "Start: $DATE"
  echo "Name: "
  echo "Initial: "
  echo "Rate: "
  echo "Command: "
  ) > /tmp/goal.txt

  $EDITOR /tmp/goal.txt

  if [ -s /tmp/goal.txt ]; then
    sed 's/.\+: //g' < /tmp/goal.txt | \
      tr '\n' '\t' | \
      sed 's/\t$/\n/g' >> "$filename"
          echo "Added to $filename"
        else
          echo "No changes made"
  fi
}

if [ $# -eq 0 ]; then
  show_status
  exit 0
fi

case "$1" in
  help)
    echo "Usage: $0 <command>"
    echo "Commands:"
    echo "  add"
    echo "  show"
    echo "  edit"
    echo "  help"
    ;;
  add)
    add_goal
    ;;
  show)
    show_status
    ;;
  edit)
    $EDITOR "$filename"
    ;;
  *)
    echo "Invalid command"
    exit 1
    ;;
esac
