#!/bin/bash

filename="$HOME/goals.txt"

if [ $# -eq 0 ]; then
  show_status
  exit 0
fi

case "$1" in
  help)
    echo "Usage: $0 <command>"
    echo "Commands:"
    echo "  add"
    echo "  show"
    echo "  edit"
    echo "  help"
    ;;
  add)
    add_goal
    ;;
  show)
    show_status
    ;;
  edit)
    $EDITOR "$filename"
    ;;
  *)
    echo "Invalid command"
    exit 1
    ;;
esac
